### ISSUE TITLE
TypeError: UUID('3ef7273b-cc4d-4b11-9237-d766c18db028') is not JSON serializable

### ISSUE THREAD

**Issue by ChrisMcKee** [mrsarm/mongotail#7]
We use mongo with the c# driver and store the UUID's in .net format GUID. 
I installed mongotail on ubuntu 14 LTS and ran the command to set the profile level with no issues. Starting mongo tail instantly blew up with this error though.

```
Traceback (most recent call last):
  File "/usr/local/bin/mongotail", line 9, in <module>
    load_entry_point('mongotail==1.0.1', 'console_scripts', 'mongotail')()
  File "/usr/local/lib/python2.7/dist-packages/mongotail/mongotail.py", line 159, in main
    tail(client, db, args.n, args.follow)
  File "/usr/local/lib/python2.7/dist-packages/mongotail/mongotail.py", line 68, in tail
    print_obj(result)
  File "/usr/local/lib/python2.7/dist-packages/mongotail/out.py", line 42, in print_obj
    query = json_encoder.encode(obj['query'])
  File "/usr/local/lib/python2.7/dist-packages/mongotail/jsondec.py", line 45, in encode
    result = super(JSONEncoder, self).encode(o)
  File "/usr/lib/python2.7/json/encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python2.7/json/encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/lib/python2.7/dist-packages/mongotail/jsondec.py", line 42, in default
    return json.JSONEncoder.default(self, o)
  File "/usr/lib/python2.7/json/encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: UUID('3ef7273b-cc4d-4b11-9237-d766c18db028') is not JSON serializable
```

The encoder doesn't seem to like UUIDs :cry:

**Comment by mrsarm** [comment]
Thanks for the patch! I just added in the next [commit](https://github.com/mrsarm/mongotail/commit/a760323b245849de545b9cb9c10020344d4ac589) a patch to format properly the UUID data type in the output console.

**Comment by ChrisMcKee** [comment]
@mrsarm Nicely done :+1:  Glad you created this, I was looking for a mongo equivalent of SQL Profiler and this is perfect :smiley:
